#!/usr/bin/env bash
# ============================================================================
# Knowsy local dev — one command to go from zero to a working dev environment.
#
# What it does:
#   1. Creates ./emulator-seed/ if missing (persistent storage between runs).
#   2. Boots the Firebase emulator suite (auth + firestore + functions +
#      storage) against project demo-knowsy, with --import + --export-on-exit
#      so Ctrl-C dumps state and the next run restores it.
#   3. Waits until the emulator is reachable.
#   4. Force-reloads firestore.rules into the running emulator via its REST
#      API (covers the case where the rules auto-reload misses a change).
#   5. Seeds the test users + starter classes (only if the emulator is empty,
#      unless --reseed is passed).
#   6. Prints the login table + URLs.
#   7. Waits on the emulator so Ctrl-C cleanly shuts it down and the export
#      writes back to ./emulator-seed/.
#
# Usage:
#   bash infra/scripts/dev.sh             # normal: boot + seed only if empty
#   bash infra/scripts/dev.sh --reseed    # force re-run the seed
#   bash infra/scripts/dev.sh --clean     # wipe ./emulator-seed/ first
#
# In a SECOND terminal, start the Vite dev server:
#   VITE_USE_EMULATORS=1 npm run dev
# Then sign in at http://localhost:5173/login.html
# ============================================================================

set -euo pipefail

# Move to repo root regardless of where the script was invoked from.
cd "$(dirname "$0")/../.."

PROJECT_ID="demo-knowsy"
SEED_DIR="./emulator-seed"
AUTH_PORT=9099
FIRESTORE_PORT=8080
FUNCTIONS_PORT=5001
STORAGE_PORT=9199
UI_PORT=4000

# ----- flags -----
RESEED=false
CLEAN=false
for arg in "$@"; do
  case "$arg" in
    --reseed) RESEED=true ;;
    --clean)  CLEAN=true ;;
    --help|-h)
      sed -n '2,28p' "$0" | sed 's/^# \?//'
      exit 0 ;;
    *) echo "Unknown flag: $arg (try --help)"; exit 1 ;;
  esac
done

# ----- preflight -----
command -v node >/dev/null || { echo "❌ node not installed"; exit 1; }
command -v npx  >/dev/null || { echo "❌ npx not installed"; exit 1; }
command -v curl >/dev/null || { echo "❌ curl not installed"; exit 1; }
[ -f firestore.rules ]               || { echo "❌ firestore.rules missing"; exit 1; }
[ -f infra/functions/seed-test-users.mjs ] || { echo "❌ seed script missing"; exit 1; }

if [ "$CLEAN" = true ]; then
  echo "🧨 --clean: nuking ${SEED_DIR}/ AND killing any stale emulator processes…"
  rm -rf "$SEED_DIR"
  # Anything left over from a previous run that didn't shut down cleanly —
  # the Java firestore/storage subprocesses, the firebase-tools wrapper,
  # any node child that's holding a port. Best-effort, swallow errors.
  pkill -f "firebase emulators" 2>/dev/null || true
  pkill -f "java.*cloud-firestore-emulator" 2>/dev/null || true
  pkill -f "java.*cloud-storage-rules-runtime" 2>/dev/null || true
  pkill -f "firebase-tools.*emulator" 2>/dev/null || true
  sleep 2
  echo "🧹 Done. Starting from zero."
fi
mkdir -p "$SEED_DIR"

# ----- bootstrap infra/functions deps if missing -----
# The Cloud Functions emulator + the seed script both need firebase-admin /
# firebase-functions installed under infra/functions/. A fresh clone has
# only the root package's node_modules; people miss the second `npm install`
# step and get cryptic "Cannot find module 'firebase-admin'" errors. Run it
# automatically the first time we detect they're missing.
if [ -f infra/functions/package.json ] && [ ! -d infra/functions/node_modules ]; then
  echo "📦 Installing infra/functions deps (one-time, ~30s)…"
  ( cd infra/functions && npm install --silent ) || {
    echo "❌ Failed to install infra/functions deps. Run 'cd infra/functions && npm install' manually."
    exit 1
  }
  echo "✅ infra/functions deps installed."
fi

# ----- bootstrap .env.local if missing (emulator defaults) -----
# Lets a fresh clone of the repo run `npm run dev:emu` without any other
# setup beyond `npm install`. The values here are deliberately fake — the
# emulator treats any project starting with `demo-` as a sandbox.
if [ ! -f .env.local ]; then
  cat > .env.local <<'ENVEOF'
# Auto-generated by infra/scripts/dev.sh on first run.
# Safe to edit / delete — gitignored. Recreated by the script if missing.
VITE_FIREBASE_API_KEY=demo-api-key
VITE_FIREBASE_PROJECT_ID=demo-knowsy
VITE_FIREBASE_APP_ID=1:0:web:demo
VITE_FIREBASE_AUTH_DOMAIN=demo-knowsy.firebaseapp.com
VITE_FIREBASE_STORAGE_BUCKET=demo-knowsy.appspot.com
VITE_FIREBASE_MESSAGING_SENDER_ID=0
VITE_USE_EMULATORS=1
ENVEOF
  echo "🆕 Wrote .env.local (emulator defaults)."
fi

# ----- helpers -----
auth_alive() { curl -fsS -o /dev/null "http://127.0.0.1:${AUTH_PORT}/" 2>/dev/null; }

count_users() {
  curl -fsS -X POST \
    -H "Authorization: Bearer owner" \
    -H "Content-Type: application/json" \
    "http://127.0.0.1:${AUTH_PORT}/identitytoolkit.googleapis.com/v1/projects/${PROJECT_ID}/accounts:query" \
    -d '{}' 2>/dev/null \
    | node -e "let d='';process.stdin.on('data',c=>d+=c).on('end',()=>{try{process.stdout.write(String(JSON.parse(d).recordsCount||0))}catch{process.stdout.write('0')}})"
}

push_rules() {
  node -e "
    const fs = require('fs');
    const content = fs.readFileSync('firestore.rules', 'utf8');
    process.stdout.write(JSON.stringify({rules:{files:[{name:'firestore.rules',content}]}}));
  " | curl -fsS -X PUT \
       -H "Content-Type: application/json" \
       -d @- \
       "http://127.0.0.1:${FIRESTORE_PORT}/emulator/v1/projects/${PROJECT_ID}:securityRules" \
       > /dev/null
}

# ----- stale lockfile cleanup -----
# firebase-tools sometimes leaves these around after a kill -9, and they
# prevent the next emulator boot with a confusing "already running" error.
rm -f .firebase/hub.json .firebase/firestore_export 2>/dev/null || true

# ----- boot (or attach to an already-running emulator) -----
EMULATOR_PID=""
if auth_alive; then
  echo "✅ Emulator already running on port ${AUTH_PORT} — will reuse it."
else
  echo "🚀 Booting Firebase emulator suite (project=${PROJECT_ID})…"
  npx firebase emulators:start \
    --only auth,firestore,functions,storage \
    --project "$PROJECT_ID" \
    --import="$SEED_DIR" \
    --export-on-exit="$SEED_DIR" &
  EMULATOR_PID=$!

  # Wait up to 90s for the auth port to start answering.
  for _ in $(seq 1 90); do
    auth_alive && break
    sleep 1
  done
  if ! auth_alive; then
    echo "❌ Emulator didn't come up in 90s. Check the logs above."
    kill -- "-$EMULATOR_PID" 2>/dev/null || true
    exit 1
  fi
  echo "✅ Emulator is up."
fi

# ----- force-reload firestore.rules -----
echo ""
echo "📡 Pushing firestore.rules into the running Firestore emulator…"
if push_rules; then
  echo "✅ Rules pushed (any 'is list' / null-value error from earlier should be gone)."
else
  echo "⚠️  Rules push failed. The emulator may not have hot-reloaded; ./firestore.rules will still take effect on the next emulator restart."
fi

# ----- seed if empty (or --reseed) -----
echo ""
USER_COUNT=$(count_users || echo 0)
if [ "$RESEED" = true ] || [ "$USER_COUNT" = "0" ]; then
  echo "🌱 Seeding test users + classes…"
  node infra/functions/seed-test-users.mjs
else
  echo "✅ Emulator already has ${USER_COUNT} user(s) — skipping seed. (Use --reseed to force.)"
fi

# ----- ready -----
cat <<EOF

────────────────────────────────────────────────────────────────────
 Knowsy dev environment is ready
────────────────────────────────────────────────────────────────────
 Emulator UI     http://127.0.0.1:${UI_PORT}
 Auth            http://127.0.0.1:${AUTH_PORT}
 Firestore       http://127.0.0.1:${FIRESTORE_PORT}
 Functions       http://127.0.0.1:${FUNCTIONS_PORT}
 Storage         http://127.0.0.1:${STORAGE_PORT}
────────────────────────────────────────────────────────────────────
 Logins
   Teacher   dov@test.com    knowsy2026
   Student   ava@test.com    knowsy2026
 Class join codes
   ECE 224   CPP224
   ECE 332   LOG332
────────────────────────────────────────────────────────────────────
 Next: in a SECOND terminal, start the Vite dev server:
   VITE_USE_EMULATORS=1 npm run dev
 Then sign in at http://localhost:5173/login.html

 Ctrl-C here exits the emulator and exports state to ${SEED_DIR}/
 (next ./dev.sh restores it automatically — no re-seeding needed).
────────────────────────────────────────────────────────────────────

EOF

# ----- block on the emulator process so Ctrl-C terminates it cleanly -----
if [ -n "$EMULATOR_PID" ]; then
  # Forward signals to the emulator so its export-on-exit handler runs.
  trap 'echo ""; echo "🛑 Stopping emulator (state will be exported to '"$SEED_DIR"')…"; kill -INT "$EMULATOR_PID" 2>/dev/null || true' INT TERM
  wait "$EMULATOR_PID" || true
  echo "✅ Emulator shut down. State exported."
else
  echo "(Emulator was already running — this script is done. The other terminal still owns the lifecycle.)"
fi
